version: '3.8'

services:
  app:
    build: .
    container_name: helpcenter-crawler
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod,secret
      - GNE_USERNAME=${GNE_USERNAME}
      - GNE_PASSWORD=${GNE_PASSWORD}
      - GNE_CODE=${GNE_CODE}
      - CHANGWON_USERNAME=${CHANGWON_USERNAME}
      - CHANGWON_PASSWORD=${CHANGWON_PASSWORD}
      - CHANGWON_CODE=${CHANGWON_CODE}
      - BUSAN_SCHOOL_USERNAME=${BUSAN_SCHOOL_USERNAME}
      - BUSAN_SCHOOL_PASSWORD=${BUSAN_SCHOOL_PASSWORD}
      - BUSAN_SCHOOL_CODE=${BUSAN_SCHOOL_CODE}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    volumes:
      - ./src/main/resources/application-secret.yml:/app/src/main/resources/application-secret.yml
    restart: no
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: helpcenter-redis
    ports:
      - "6379:6379"
    restart: no
    volumes:
      - redis-data:/data

volumes:
  redis-data: