services:
  # 백엔드 서비스
  backend:
    build:
      context: /
      dockerfile: Dockerfile
    container_name: helpcenter-backend
    ports:
      - "8082:8082"
    expose:
      - "8082"  # 컨테이너 포트 노출
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod,secret
      - SPRING_REDIS_HOST=redis-main
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    restart: unless-stopped
    depends_on:
      redis-main:
        condition: service_started
    networks:
      - helpcenter-network

  # Redis 설정
  redis-main:
    image: redis:latest
    container_name: redis-main
    environment:
      - TZ=Asia/Seoul
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - helpcenter-network

volumes:
  redis-data:

networks:
  helpcenter-network:
    driver: bridge