server:
  port: 8082

# 크롤링 실행 주기 설정 (ms 단위)
scheduler:
  crawler:
    cron: 0 0/10 8-18 * * MON-FRI  # 월요일 ~ 금요일 08시 부터 18시까지 10분마다 실행


spring:
  datasource:
    url: ${spring.datasource.url:?DB URL이 설정되지 않았습니다. application-secret.yml이 올바르게 로드되었는지 확인하세요}
    driver-class-name: ${spring.datasource.driver-class-name:?DB 드라이버가 설정되지 않았습니다. application-secret.yml을 확인하세요}
    username: ${spring.datasource.username:?DB 사용자명이 설정되지 않았습니다. application-secret.yml을 확인하세요}
    password: ${spring.datasource.password:?DB 비밀번호가 설정되지 않았습니다. application-secret.yml을 확인하세요}

  # JPA 설정 추가
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    open-in-view: false

logging:
  level:
    root: ERROR
