server:
  port: 8082

# 크롤링 실행 주기 설정 (ms 단위)
scheduler:
  crawler:
    fixed-delay: 0 0/3 8-18 * * MON-FRI  # 월요일 ~ 금요일 08시 부터 18시까지 3분마다 실행
  migration:
    cron: "0 0 19 * * MON-FRI" # 월-금 오후 7시


spring:
  datasource:
    url: ${spring.datasource.url:?DB URL이 설정되지 않았습니다. application-secret.yml이 올바르게 로드되었는지 확인하세요}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${spring.datasource.username:?DB 사용자명이 설정되지 않았습니다. application-secret.yml을 확인하세요}
    password: ${spring.datasource.password:?DB 비밀번호가 설정되지 않았습니다. application-secret.yml을 확인하세요}

  # Redis 설정
  data:
    redis:
      host: redis-main
      port: 6379
      timeout: 10000
      database: 0

  # JPA 설정 추가
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false