server:
  port: 8082

# 크롤링 실행 주기 설정 (ms 단위)
scheduler:
  crawler:
    fixed-delay: 180000  # 3분 (180,000밀리초)
  migration:
    cron: "0 0 22 * * ?"  # 매일 오후 10시에 실행


spring:
  datasource:
    url: ${spring.datasource.url:?DB URL이 설정되지 않았습니다. application-secret.yml이 올바르게 로드되었는지 확인하세요}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${spring.datasource.username:?DB 사용자명이 설정되지 않았습니다. application-secret.yml을 확인하세요}
    password: ${spring.datasource.password:?DB 비밀번호가 설정되지 않았습니다. application-secret.yml을 확인하세요}

  # Redis 설정
  data:
    redis:
      host: redis-main
      port: 6379
      timeout: 10000
      database: 0

  # JPA 설정 추가
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false